# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # https://stackoverflow.com/questions/17845637/how-to-change-vagrant-default-machine-name
  config.vm.define     "microk8s"
  config.vm.hostname = "microk8s"

  # https://www.vagrantup.com/docs/vagrantfile/ssh_settings#config-ssh-insert_key
  config.ssh.insert_key  = false
  config.ssh.compression = false
  config.ssh.extra_args  = "-4"

  config.vm.box = "generic/ubuntu2004"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.1.11" # VMware Network Adapter VMnet1

  # Provider-specific configuration
  config.vm.provider "vmware_desktop" do |v|
    #v.gui = "true"
    v.clone_directory = "c:/vmstore/vagrant"
    v.vmx["memsize"]  = "6144"
    v.vmx["numvcpus"] = "4"
    v.vmx["cpuid.coresPerSocket"] = "4"
    v.vmx["mainMem.useNamedFile"] = "FALSE"  # disable .vmem
    v.vmx["disk.EnableUUID"] = "TRUE"        # https://www.suse.com/support/kb/doc/?id=000016951
    v.vmx["ulm.disableMitigations"] = "TRUE" # https://kb.vmware.com/s/article/79832
  end

  config.vm.provision "shell", path: "../vagrant-scripts/update-ubuntu-apt-source-list.sh"
  config.vm.provision "shell", path: "install-microk8s.sh"
end
