#Requires -version 5
$_MY_BACKUP_ROOT = 'e:\backup'


$BACKUP_SRC_FILE = @"
BACKUP_SRC_PATH,BACKUP_DST_PATH
$_MY_BACKUP_ROOT\USERPROFILE\.bash*,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\.git*,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\.minttyrc,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\.softlayer*,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\_vimrc,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\_viminfo,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\.viminfo,$env:USERPROFILE
$_MY_BACKUP_ROOT\USERPROFILE\*.ini,$env:USERPROFILE
$_MY_BACKUP_ROOT\APPDATA\ConEmu.xml,$env:APPDATA
"@ -split "`n" | % { $_.trim() } | ConvertFrom-Csv


$BACKUP_SRC_DIR = @"
BACKUP_SRC_PATH,BACKUP_DST_PATH
$_MY_BACKUP_ROOT\USERPROFILE\Documents\Telegram,$env:USERPROFILE\DOCUMENTS\Telegram
$_MY_BACKUP_ROOT\USERPROFILE\Documents\go,$env:USERPROFILE\DOCUMENTS\go
$_MY_BACKUP_ROOT\USERPROFILE\Documents\keepass,$env:USERPROFILE\DOCUMENTS\keepass
$_MY_BACKUP_ROOT\USERPROFILE\Documents\My Received Files,$env:USERPROFILE\DOCUMENTS\My Received Files
$_MY_BACKUP_ROOT\USERPROFILE\Documents\RemoteDesktop,$env:USERPROFILE\DOCUMENTS\RemoteDesktop
$_MY_BACKUP_ROOT\USERPROFILE\Documents\ruby_ssl_certs,$env:USERPROFILE\DOCUMENTS\ruby_ssl_certs
$_MY_BACKUP_ROOT\USERPROFILE\Documents\ScalaProjects,$env:USERPROFILE\DOCUMENTS\ScalaProjects
$_MY_BACKUP_ROOT\USERPROFILE\Documents\SublimeProjects,$env:USERPROFILE\DOCUMENTS\SublimeProjects
$_MY_BACKUP_ROOT\USERPROFILE\Documents\Virtual Machines,$env:USERPROFILE\DOCUMENTS\Virtual Machines
$_MY_BACKUP_ROOT\USERPROFILE\Documents\WindowsPowerShell,$env:USERPROFILE\DOCUMENTS\WindowsPowerShell
$_MY_BACKUP_ROOT\USERPROFILE\Documents\Calibre,$env:USERPROFILE\Documents\Calibre
$_MY_BACKUP_ROOT\USERPROFILE\Documents\Bitbucket,$env:USERPROFILE\Documents\Bitbucket
$_MY_BACKUP_ROOT\USERPROFILE\Documents\Fiddler2,$env:USERPROFILE\Documents\Fiddler2
$_MY_BACKUP_ROOT\USERPROFILE\Documents\GitHub,$env:USERPROFILE\Documents\GitHub
$_MY_BACKUP_ROOT\USERPROFILE\Favorites,$env:USERPROFILE\Favorites
$_MY_BACKUP_ROOT\USERPROFILE\Dropbox,$env:USERPROFILE\Dropbox
$_MY_BACKUP_ROOT\USERPROFILE\Downloads,$env:USERPROFILE\Downloads
$_MY_BACKUP_ROOT\USERPROFILE\Pictures,$env:USERPROFILE\Pictures
$_MY_BACKUP_ROOT\USERPROFILE\Desktop,$env:USERPROFILE\Desktop
$_MY_BACKUP_ROOT\USERPROFILE\devtools,$env:USERPROFILE\devtools
$_MY_BACKUP_ROOT\USERPROFILE\.ssh,$env:USERPROFILE\.ssh
$_MY_BACKUP_ROOT\USERPROFILE\.aws,$env:USERPROFILE\.aws
$_MY_BACKUP_ROOT\USERPROFILE\.azure,$env:USERPROFILE\.azure
$_MY_BACKUP_ROOT\USERPROFILE\.chef,$env:USERPROFILE\.chef
$_MY_BACKUP_ROOT\USERPROFILE\.CLion2016.3,$env:USERPROFILE\.CLion2016.3
$_MY_BACKUP_ROOT\USERPROFILE\.codeintel,$env:USERPROFILE\.codeintel
$_MY_BACKUP_ROOT\USERPROFILE\.config,$env:USERPROFILE\.config
$_MY_BACKUP_ROOT\USERPROFILE\.DataGrip2017.1,$env:USERPROFILE\.DataGrip2017.1
$_MY_BACKUP_ROOT\USERPROFILE\.docker,$env:USERPROFILE\.docker
$_MY_BACKUP_ROOT\USERPROFILE\.eclipse,$env:USERPROFILE\.eclipse
$_MY_BACKUP_ROOT\USERPROFILE\.gem,$env:USERPROFILE\.gem
$_MY_BACKUP_ROOT\USERPROFILE\.IntelliJIdea2017.1,$env:USERPROFILE\.IntelliJIdea2017.1
$_MY_BACKUP_ROOT\USERPROFILE\.sbt,$env:USERPROFILE\.sbt
$_MY_BACKUP_ROOT\USERPROFILE\.ssh,$env:USERPROFILE\.ssh
$_MY_BACKUP_ROOT\USERPROFILE\.vscode,$env:USERPROFILE\.vscode
$_MY_BACKUP_ROOT\USERPROFILE\.VirtualBox,$env:USERPROFILE\.VirtualBox
$_MY_BACKUP_ROOT\USERPROFILE\IdeaProjects,$env:USERPROFILE\IdeaProjects
$_MY_BACKUP_ROOT\USERPROFILE\ClionProjects,$env:USERPROFILE\ClionProjects
$_MY_BACKUP_ROOT\USERPROFILE\bin,$env:USERPROFILE\bin
$_MY_BACKUP_ROOT\USERPROFILE\vimfiles,$env:USERPROFILE\vimfiles
$_MY_BACKUP_ROOT\USERPROFILE\workspace,$env:USERPROFILE\workspace
$_MY_BACKUP_ROOT\USERPROFILE\VirtualBox VMs,$env:USERPROFILE\VirtualBox VMs
$_MY_BACKUP_ROOT\msys64,c:\msys64
$_MY_BACKUP_ROOT\temp,c:\temp
$_MY_BACKUP_ROOT\APPDATA\.emacs.d,$env:APPDATA\.emacs.d
$_MY_BACKUP_ROOT\APPDATA\.kde,$env:APPDATA\.kde
$_MY_BACKUP_ROOT\APPDATA\AC3Filter,$env:APPDATA\AC3Filter
$_MY_BACKUP_ROOT\APPDATA\Atom,$env:APPDATA\Atom
$_MY_BACKUP_ROOT\APPDATA\Code,$env:APPDATA\Code
$_MY_BACKUP_ROOT\APPDATA\CodeBlocks,$env:APPDATA\CodeBlocks
$_MY_BACKUP_ROOT\APPDATA\Dev-Cpp,$env:APPDATA\Dev-Cpp
$_MY_BACKUP_ROOT\APPDATA\Docker,$env:APPDATA\Docker
$_MY_BACKUP_ROOT\APPDATA\FastStone,$env:APPDATA\FastStone
$_MY_BACKUP_ROOT\APPDATA\FileZilla,$env:APPDATA\FileZilla
$_MY_BACKUP_ROOT\APPDATA\Foxit Software,$env:APPDATA\Foxit Software
$_MY_BACKUP_ROOT\APPDATA\ghc,$env:APPDATA\ghc
$_MY_BACKUP_ROOT\APPDATA\GHISLER,$env:APPDATA\GHISLER
$_MY_BACKUP_ROOT\APPDATA\gnupg,$env:APPDATA\gnupg
$_MY_BACKUP_ROOT\APPDATA\GRETECH,$env:APPDATA\GRETECH
$_MY_BACKUP_ROOT\APPDATA\HNC,$env:APPDATA\HNC
$_MY_BACKUP_ROOT\APPDATA\JetBrains,$env:APPDATA\JetBrains
$_MY_BACKUP_ROOT\APPDATA\JGoodies,$env:APPDATA\JGoodies
$_MY_BACKUP_ROOT\APPDATA\KeePass,$env:APPDATA\KeePass
$_MY_BACKUP_ROOT\APPDATA\Kitematic,$env:APPDATA\Kitematic
$_MY_BACKUP_ROOT\APPDATA\LINQPad,$env:APPDATA\LINQPad
$_MY_BACKUP_ROOT\APPDATA\Logishrd,$env:APPDATA\Logishrd
$_MY_BACKUP_ROOT\APPDATA\MarkdownPad 2,$env:APPDATA\MarkdownPad 2
$_MY_BACKUP_ROOT\APPDATA\MediaInfo,$env:APPDATA\MediaInfo
$_MY_BACKUP_ROOT\APPDATA\Mozilla,$env:APPDATA\Mozilla
$_MY_BACKUP_ROOT\APPDATA\MySQL,$env:APPDATA\MySQL
$_MY_BACKUP_ROOT\APPDATA\npm,$env:APPDATA\npm
$_MY_BACKUP_ROOT\APPDATA\NuGet,$env:APPDATA\NuGet
$_MY_BACKUP_ROOT\APPDATA\OpenLiveWriter,$env:APPDATA\OpenLiveWriter
$_MY_BACKUP_ROOT\APPDATA\Opera Software,$env:APPDATA\Opera Software
$_MY_BACKUP_ROOT\APPDATA\packer.d,$env:APPDATA\packer.d
$_MY_BACKUP_ROOT\APPDATA\S3Browser,$env:APPDATA\S3Browser
$_MY_BACKUP_ROOT\APPDATA\slack,$env:APPDATA\slack
$_MY_BACKUP_ROOT\APPDATA\Sublime Text 2,$env:APPDATA\Sublime Text 2
$_MY_BACKUP_ROOT\APPDATA\Subversion,$env:APPDATA\Subversion
$_MY_BACKUP_ROOT\APPDATA\terraform.d,$env:APPDATA\terraform.d
$_MY_BACKUP_ROOT\APPDATA\TortoiseSVN,$env:APPDATA\TortoiseSVN
$_MY_BACKUP_ROOT\APPDATA\Typora,$env:APPDATA\Typora
$_MY_BACKUP_ROOT\APPDATA\VanDyke,$env:APPDATA\VanDyke
$_MY_BACKUP_ROOT\APPDATA\vlc,$env:APPDATA\vlc
$_MY_BACKUP_ROOT\APPDATA\VMware,$env:APPDATA\VMware
$_MY_BACKUP_ROOT\APPDATA\WinAuth,$env:APPDATA\WinAuth
$_MY_BACKUP_ROOT\APPDATA\Windows Azure Powershell,$env:APPDATA\Windows Azure Powershell
$_MY_BACKUP_ROOT\LOCALAPPDATA\Atlassian,$env:LOCALAPPDATA\Atlassian
$_MY_BACKUP_ROOT\LOCALAPPDATA\Microsoft\Remote Desktop Connection Manager,$env:LOCALAPPDATA\Microsoft\Remote Desktop Connection Manager
$_MY_BACKUP_ROOT\LOCALAPPDATA\slack,$env:LOCALAPPDATA\slack
$_MY_BACKUP_ROOT\LOCALAPPDATA\SourceTree,$env:LOCALAPPDATA\SourceTree
"@ -split "`n" | % { $_.trim() } | ConvertFrom-Csv


function Start-DirBackup ($SRC_PATH, $DST_PATH) {
  if ( ! (Test-Path $DST_PATH)) { mkdir -Force $DST_PATH | Out-Null }
  robocopy.exe "$SRC_PATH" "$DST_PATH" /mir /timfix /np /nfl /ndl
}

function Start-FileBackup ($SRC_PATH, $DST_PATH) {
  if ( ! (Test-Path $DST_PATH)) { mkdir -Force $DST_PATH | Out-Null }
  Copy-Item -Force "$SRC_PATH" "$DST_PATH" | Out-Null
}



# Folders
$BACKUP_SRC_DIR_num = ($BACKUP_SRC_DIR | Measure-Object).Count
for ( $i=0; $i -lt $BACKUP_SRC_DIR_num; $i++ )
{
  Start-DirBackup $BACKUP_SRC_DIR[$i].BACKUP_SRC_PATH $BACKUP_SRC_DIR[$i].BACKUP_DST_PATH
}


# Files
$BACKUP_SRC_FILE_num = ($BACKUP_SRC_FILE | Measure-Object).Count
for ( $i=0; $i -lt $BACKUP_SRC_FILE_num; $i++ )
{
  Start-FileBackup $BACKUP_SRC_FILE[$i].BACKUP_SRC_PATH $BACKUP_SRC_FILE[$i].BACKUP_DST_PATH
}

